twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    globals:
        categories: '@App\Repository\CategorieRepository' # Use service
when@test:
  twig:
    strict_variables: true
    
